// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT7-YRzXn5dKfoIhzkSivBuKOxz8Hxqro',
    appId: '1:967834798481:web:ab27d0cc467f73421ef230',
    messagingSenderId: '967834798481',
    projectId: 'adopets-c99db',
    authDomain: 'adopets-c99db.firebaseapp.com',
    storageBucket: 'adopets-c99db.firebasestorage.app',
    measurementId: 'G-Z914Y21TJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtuSXynpuw63-xfx0MRlYB-Ib79jLsV1E',
    appId: '1:967834798481:android:19ad2718a62d1bb51ef230',
    messagingSenderId: '967834798481',
    projectId: 'adopets-c99db',
    storageBucket: 'adopets-c99db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBe7ngMFsPIuOnxPx8WHgrWH9yB1C2604',
    appId: '1:967834798481:ios:42b41fbd4f8421f91ef230',
    messagingSenderId: '967834798481',
    projectId: 'adopets-c99db',
    storageBucket: 'adopets-c99db.firebasestorage.app',
    iosBundleId: 'com.adopets.appMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBe7ngMFsPIuOnxPx8WHgrWH9yB1C2604',
    appId: '1:967834798481:ios:42b41fbd4f8421f91ef230',
    messagingSenderId: '967834798481',
    projectId: 'adopets-c99db',
    storageBucket: 'adopets-c99db.firebasestorage.app',
    iosBundleId: 'com.adopets.appMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT7-YRzXn5dKfoIhzkSivBuKOxz8Hxqro',
    appId: '1:967834798481:web:ddcd627efbc9a30e1ef230',
    messagingSenderId: '967834798481',
    projectId: 'adopets-c99db',
    authDomain: 'adopets-c99db.firebaseapp.com',
    storageBucket: 'adopets-c99db.firebasestorage.app',
    measurementId: 'G-YRPYLN3WBF',
  );
}
